version: "3"
services:
  client:
    build: "./client"
    ports:
      - "3000:3000"
    volumes:
      - /src/node_modules
      - ./client:/src
      - dist:/src/build
    depends_on: 
      - server

  server:
    build: "./server"
    ports:
      - "3001:3000"
    volumes:
      - /src/node_modules
      - ./server:/src

  nginx:
    image: nginx:latest
    ports:
      - "8080:8080"
    volumes:
      - dist:/srv/www/static
      - ./default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - client
      - server

volumes:
  dist: